name: Build Desktop Applications

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    types: [tag]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            artifact-name: windows-build
          - os: ubuntu-latest
            artifact-name: linux-build
          - os: macos-latest
            artifact-name: macos-build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact-name }}
        path: |
          dist/**
          !dist/**/*.map

    - name: Generate version
      run: |
        echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/')

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.AppImage
          dist/*.dmg
        token: ${{ secrets.GH_TOKEN }}
        tag_name: ${{ env.NEW_VERSION }}
        body: Release notes generated from CI
      if: startsWith(github.ref, 'refs/tags/')
